learn_templates/basic_app/urls.py
from django.urls import path
from basic_app import views

# TEMPLATE TAGGING
app_name = 'basic_app'

urlpatterns=[
		path('', views.base, name='base'),
		path('relative/', views.relative, name='relative'),
		path('other/', views.other, name='other'),

]

learn_templates/learn_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('basic_app/', include('basic_app.urls'))
]

learn_templates/basic_app/models.py
from django.db import models

# Create your models here.

learn_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.

def base(request):
	return render(request, 'basic_app/basic_app.html')

def index(request):
	dict1={'text':'hello world', 'num':100}
	return render(request, 'basic_app/index.html',dict1)

def other(request):
	return render(request, 'basic_app/other.html')

def relative(request):
	return render(request, 'basic_app/rel_url.html')

learn_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>
    {% block title %}
    {% endblock %}
  </title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

{% block body %}
{% endblock %}


<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

learn_templates/templates/basic_app/basic_app.html
{% extends "basic_app/base.html" %}

{% block title %}
Inside App
{% endblock %}

{% block body %}

	<h1>You are inside Basic App</h1>

	GO TO <a href="{% url 'basic_app:other' %}">OTHER PAGE</a> <br>
	GO TO <a href="{% url 'basic_app:relative' %}">RELATIVE PAGE</a> <br>
	GO TO <a href="{% url 'admin:index' %}">ADMIN PAGE</a>  <br>
	GO TO <a href="{% url 'index' %}">INDEX PAGE</a>

{% endblock %}

learn_templates/templates/basic_app/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Index</title>
	<link rel="stylesheet" href="">
</head>
<body>
	<h1>Welcome to Index</h1>
	<h1>{{text|cut:'world'}}</h1>
	<h1>{{num}}</h1>

	
</body>
</html>

learn_templates/templates/basic_app/other.html
{% extends "basic_app/base.html" %}

{% block title %}
Other
{% endblock %}

{% block body %}

<h1>THis is OTHER PAGE</h1>



{% endblock %}

learn_templates/templates/basic_app/rel_url.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>Relative</title>
	<link rel="stylesheet" href="">
</head>
<body>
	<h1>Welcome to Relative Url Template </h1>
	
</body>
</html>